# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - checkdoc
          - pylava
          - mypy

    steps:
      - uses: actions/checkout@v2
      - name: tox ${{ matrix.linter }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.linter }}
        with:
          args: tox

  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: docker://mosquito/aiormq-rabbitmq
        ports:
          - 5672:5672

    strategy:
      matrix:
        toxenv:
          - py37
          - py38
          - py39
          - py310
          - py37-uvloop
          - py38-uvloop
          - py39-uvloop
          - py310-uvloop

    steps:
      - uses: actions/checkout@v2

      - name: tox ${{ matrix.toxenv }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: yes
          AMQP_URL: amqp://guest:guest@rabbitmq
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          args: /bin/bash -c "wait-for-port rabbitmq:5672 && tox"
